# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabBar = QTabBar(self.centralwidget)
        self.tabBar.setObjectName("tabBar")
        self.verticalLayout_2.addWidget(self.tabBar)
        self.saImgDisplay = QtWidgets.QScrollArea(self.centralwidget)
        self.saImgDisplay.setWidgetResizable(True)
        self.saImgDisplay.setObjectName("saImgDisplay")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 694, 493))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblImgDisplay = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblImgDisplay.setText("")
        self.lblImgDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.lblImgDisplay.setObjectName("lblImgDisplay")
        self.horizontalLayout.addWidget(self.lblImgDisplay)
        self.saImgDisplay.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.saImgDisplay)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.groupBoxInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxInfo.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBoxInfo.setObjectName("groupBoxInfo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxInfo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblImageSize = QtWidgets.QLabel(self.groupBoxInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblImageSize.sizePolicy().hasHeightForWidth())
        self.lblImageSize.setSizePolicy(sizePolicy)
        self.lblImageSize.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblImageSize.setObjectName("lblImageSize")
        self.verticalLayout.addWidget(self.lblImageSize)
        self.lblZoomFactor = QtWidgets.QLabel(self.groupBoxInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblZoomFactor.sizePolicy().hasHeightForWidth())
        self.lblZoomFactor.setSizePolicy(sizePolicy)
        self.lblZoomFactor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblZoomFactor.setObjectName("lblZoomFactor")
        self.verticalLayout.addWidget(self.lblZoomFactor)
        self.horizontalLayout_2.addWidget(self.groupBoxInfo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuProcessing = QtWidgets.QMenu(self.menubar)
        self.menuProcessing.setObjectName("menuProcessing")
        self.menuDerivative_Filter = QtWidgets.QMenu(self.menuProcessing)
        self.menuDerivative_Filter.setObjectName("menuDerivative_Filter")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/view/res/icons/document-open.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/view/res/icons/edit-undo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon1)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/view/res/icons/edit-redo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon2)
        self.actionRedo.setObjectName("actionRedo")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/view/res/icons/zoom-in.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon3)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/view/res/icons/zoom-out.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon4)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionDefineScale = QtWidgets.QAction(MainWindow)
        self.actionDefineScale.setObjectName("actionDefineScale")
        self.actionDefineAreas = QtWidgets.QAction(MainWindow)
        self.actionDefineAreas.setObjectName("actionDefineAreas")
        self.actionSegmentation = QtWidgets.QAction(MainWindow)
        self.actionSegmentation.setObjectName("actionSegmentation")
        self.actionContrast = QtWidgets.QAction(MainWindow)
        self.actionContrast.setObjectName("actionContrast")
        self.actionFiberDiameter = QtWidgets.QAction(MainWindow)
        self.actionFiberDiameter.setObjectName("actionFiberDiameter")
        self.actionFiberOrientation = QtWidgets.QAction(MainWindow)
        self.actionFiberOrientation.setObjectName("actionFiberOrientation")
        self.actionDerivativeSobel = QtWidgets.QAction(MainWindow)
        self.actionDerivativeSobel.setObjectName("actionDerivativeSobel")
        self.actionDerivativeLaPlace = QtWidgets.QAction(MainWindow)
        self.actionDerivativeLaPlace.setObjectName("actionDerivativeLaPlace")
        self.actionSmoothingFilter = QtWidgets.QAction(MainWindow)
        self.actionSmoothingFilter.setObjectName("actionSmoothingFilter")
        self.actionSharpen = QtWidgets.QAction(MainWindow)
        self.actionSharpen.setObjectName("actionSharpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExport)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionZoomIn)
        self.menuEdit.addAction(self.actionZoomOut)
        self.menuEdit.addAction(self.actionDefineScale)
        self.menuEdit.addAction(self.actionDefineAreas)
        self.menuDerivative_Filter.addAction(self.actionDerivativeSobel)
        self.menuDerivative_Filter.addAction(self.actionDerivativeLaPlace)
        self.menuProcessing.addAction(self.actionSmoothingFilter)
        self.menuProcessing.addAction(self.menuDerivative_Filter.menuAction())
        self.menuProcessing.addAction(self.actionSegmentation)
        self.menuProcessing.addAction(self.actionContrast)
        self.menuProcessing.addAction(self.actionSharpen)
        self.menuAnalysis.addAction(self.actionFiberDiameter)
        self.menuAnalysis.addAction(self.actionFiberOrientation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuProcessing.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionZoomIn)
        self.toolBar.addAction(self.actionZoomOut)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBoxInfo.setTitle(_translate("MainWindow", "Information"))
        self.lblImageSize.setText(_translate("MainWindow", "Image size"))
        self.lblZoomFactor.setText(_translate("MainWindow", "Zoom factor"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuProcessing.setTitle(_translate("MainWindow", "Processing"))
        self.menuDerivative_Filter.setTitle(_translate("MainWindow", "Derivative Filter"))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionZoomIn.setText(_translate("MainWindow", "Zoom in"))
        self.actionZoomOut.setText(_translate("MainWindow", "Zoom out"))
        self.actionDefineScale.setText(_translate("MainWindow", "Define scale"))
        self.actionDefineAreas.setText(_translate("MainWindow", "Define areas"))
        self.actionSegmentation.setText(_translate("MainWindow", "Segmentation"))
        self.actionContrast.setText(_translate("MainWindow", "Contrast"))
        self.actionFiberDiameter.setText(_translate("MainWindow", "Fiber diameter"))
        self.actionFiberOrientation.setText(_translate("MainWindow", "Fiber orientation"))
        self.actionDerivativeSobel.setText(_translate("MainWindow", "Sobel"))
        self.actionDerivativeLaPlace.setText(_translate("MainWindow", "LaPlace"))
        self.actionSmoothingFilter.setText(_translate("MainWindow", "Smoothing Filter"))
        self.actionSharpen.setText(_translate("MainWindow", "Sharpen"))

from PyQt5.QtWidgets import QTabBar
import resources_rc
