# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saImgDisplay = QtWidgets.QScrollArea(self.centralwidget)
        self.saImgDisplay.setWidgetResizable(True)
        self.saImgDisplay.setObjectName("saImgDisplay")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 696, 501))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblImgDisplay = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lblImgDisplay.setText("")
        self.lblImgDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.lblImgDisplay.setObjectName("lblImgDisplay")
        self.horizontalLayout.addWidget(self.lblImgDisplay)
        self.saImgDisplay.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.saImgDisplay)
        self.groupBoxInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxInfo.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBoxInfo.setObjectName("groupBoxInfo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxInfo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblImageSize = QtWidgets.QLabel(self.groupBoxInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblImageSize.sizePolicy().hasHeightForWidth())
        self.lblImageSize.setSizePolicy(sizePolicy)
        self.lblImageSize.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblImageSize.setObjectName("lblImageSize")
        self.verticalLayout.addWidget(self.lblImageSize)
        self.lblZoomFactor = QtWidgets.QLabel(self.groupBoxInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblZoomFactor.sizePolicy().hasHeightForWidth())
        self.lblZoomFactor.setSizePolicy(sizePolicy)
        self.lblZoomFactor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblZoomFactor.setObjectName("lblZoomFactor")
        self.verticalLayout.addWidget(self.lblZoomFactor)
        self.horizontalLayout_2.addWidget(self.groupBoxInfo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuProcessing = QtWidgets.QMenu(self.menubar)
        self.menuProcessing.setObjectName("menuProcessing")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/view/res/icons/document-open.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/view/res/icons/edit-undo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon1)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/view/res/icons/edit-redo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon2)
        self.actionRedo.setObjectName("actionRedo")
        self.actionZoom_in = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/view/res/icons/zoom-in.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_in.setIcon(icon3)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/view/res/icons/zoom-out.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out.setIcon(icon4)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.actionDefine_scale = QtWidgets.QAction(MainWindow)
        self.actionDefine_scale.setObjectName("actionDefine_scale")
        self.actionDefine_areas = QtWidgets.QAction(MainWindow)
        self.actionDefine_areas.setObjectName("actionDefine_areas")
        self.actionFilter = QtWidgets.QAction(MainWindow)
        self.actionFilter.setObjectName("actionFilter")
        self.actionSegmentation = QtWidgets.QAction(MainWindow)
        self.actionSegmentation.setObjectName("actionSegmentation")
        self.actionContrast = QtWidgets.QAction(MainWindow)
        self.actionContrast.setObjectName("actionContrast")
        self.actionFiber_diameter = QtWidgets.QAction(MainWindow)
        self.actionFiber_diameter.setObjectName("actionFiber_diameter")
        self.actionFiber_orientation = QtWidgets.QAction(MainWindow)
        self.actionFiber_orientation.setObjectName("actionFiber_orientation")
        self.actionTest2 = QtWidgets.QAction(MainWindow)
        self.actionTest2.setObjectName("actionTest2")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExport)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionZoom_in)
        self.menuEdit.addAction(self.actionZoom_out)
        self.menuEdit.addAction(self.actionDefine_scale)
        self.menuEdit.addAction(self.actionDefine_areas)
        self.menuProcessing.addAction(self.actionFilter)
        self.menuProcessing.addAction(self.actionSegmentation)
        self.menuProcessing.addAction(self.actionContrast)
        self.menuAnalysis.addAction(self.actionFiber_diameter)
        self.menuAnalysis.addAction(self.actionFiber_orientation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuProcessing.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionZoom_in)
        self.toolBar.addAction(self.actionZoom_out)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBoxInfo.setTitle(_translate("MainWindow", "Information"))
        self.lblImageSize.setText(_translate("MainWindow", "Image size"))
        self.lblZoomFactor.setText(_translate("MainWindow", "Zoom factor"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuProcessing.setTitle(_translate("MainWindow", "Processing"))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionZoom_in.setText(_translate("MainWindow", "Zoom in"))
        self.actionZoom_out.setText(_translate("MainWindow", "Zoom out"))
        self.actionDefine_scale.setText(_translate("MainWindow", "Define scale"))
        self.actionDefine_areas.setText(_translate("MainWindow", "Define areas"))
        self.actionFilter.setText(_translate("MainWindow", "Filter"))
        self.actionSegmentation.setText(_translate("MainWindow", "Segmentation"))
        self.actionContrast.setText(_translate("MainWindow", "Contrast"))
        self.actionFiber_diameter.setText(_translate("MainWindow", "Fiber diameter"))
        self.actionFiber_orientation.setText(_translate("MainWindow", "Fiber orientation"))
        self.actionTest2.setText(_translate("MainWindow", "test2"))

import resources_rc
